# Generated by Django 4.0 on 2021-12-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='sd_volume_max',
        ),
    ]
